### ISSUE TITLE
recent update broke server-side rendering

### ISSUE THREAD

**Issue by tennox** [seeratawan01/vue-lazytube#28]
**Describe the bug**
Upgrade from 1.0.4 to latest 1.1.1 (can bisect tomorrow) broke SSR:
```
ReferenceError: document is not defined
     at c (node_modules/vue-lazytube/dist/vue-lazytube.umd.min.js:2:83266)
     at v (node_modules/vue-lazytube/dist/vue-lazytube.umd.min.js:2:84526)
     at u (node_modules/vue-lazytube/dist/vue-lazytube.umd.min.js:2:83190)
     at t.exports (node_modules/vue-lazytube/dist/vue-lazytube.umd.min.js:2:84859)
     at assets/js/vendors~page--src--pages--index-vue.9796b736.js:13768:87012
```

**To Reproduce**
1. Use vue-lazytube in nodejs rendering
(Can provide more details tomorrow)

**Expected behavior**
Working SSR.
Maybe it is out of scope for you and I have to disable it on server side, but would be great if not :)

**Comment by priverop** [comment]
The same happens in Nuxt 2.
